version: '3.8'

services: 
  etcd_server: 
    image: bitnami/etcd:3.5.2
    container_name: etcd_container
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCDCTL: 3
      ALLOW_NONE_AUTHENTICATION: yes

