version: '3'
services:
  rabbitmq_compose:
    image: rabbitmq:management
    container_name: rabbitmq_container
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=123456"
