version: '3'
services:
  mysql_compose:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      # - ./mydir:/mydir
      # 文件挂载
      # - ./datadir:/var/lib/mysql
      # 挂载目录
      - ./conf/my.cnf:/etc/mysql/my.cnf
      # 挂载 my.cnf 配置文件
      # - ./docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=/1/2/3"
      # 设置密码
      - "MYSQL_DATABASE=big_john"
      # 设置默认数据库
      - "TZ=Asia/Shanghai"
      # 设置时区
