version: "3.9"
services:
 postgres:
  image: postgres:15
  container_name: postgres
  environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  ports:
    - 5432:5432
  # volumes:
   # - /data/compose/postgresql/data:/var/lib/postgresql/data
